osx_image: xcode10.2
language: objective-c
sudo: false
xcode_project: CIDemo.xcodeproj
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
  - FASTLANE_LANE=ci_commit
branches:
  only:
  - master

before_script:
  - env
  - locale
  - gem install xcpretty --no-document --quiet
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - set -o pipefail
  - xcodebuild build -project CIDemo.xcodeproj -scheme 'CIDemo' -destination 'platform=iOS Simulator,name=iPhone XS' -configuration Debug CODE_SIGNING_ALLOWED=NO | xcpretty -c

  - echo test
  - xcodebuild clean test -project CIDemo.xcodeproj -scheme 'CIDemoTests' -destination 'platform=iOS Simulator,name=iPhone XS' -configuration Debug -UseModernBuildSystem=NO CODE_SIGNING_ALLOWED=NO | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)
