osx_image: xcode10
language: objective-c
xcode_project: CIDemo.xcodeproj
branches:
  only:
  - master

script:
  - xcodebuild -project CIDemo.xcodeproj -scheme "CIDemo" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest'
