osx_image: xcode10
language: objective-c
sudo: false
xcode_project: CIDemo.xcodeproj
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
  - FASTLANE_LANE=ci_commit
branches:
  only:
  - master

before_script:
  # - brew update
  - brew upgrade xctool

script:
  - xctool -project CIDemo.xcodeproj -scheme 'CIDemo' -sdk iphonesimulator build
  #- xcodebuild clean
  #- xcodebuild -project CIDemo.xcodeproj -scheme CIDemo -destination 'platform=iOS Simulator,name=iPhone XS Max,OS=12.0'
  #- xcodebuild -project CIDemo.xcodeproj -scheme CIDemo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest'
  #- xcodebuild clean test -workspace ApplepieDemo/ApplepieDemo.xcworkspace -scheme ApplepieDemo -destination 'platform=iOS Simulator,name=iPhone XS Max,OS=12.0' -enableCodeCoverage YES | bundle exec xcpretty
